# Generated by Django 3.0.5 on 2020-07-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='noteadmin',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
